# Generated by Django 4.2.18 on 2026-06-23 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('adresse_description', models.CharField(blank=True, help_text="Description textuelle de l'emplacement (ex: 'Devant le marché, côté est')", max_length=255)),
                ('type_dechet', models.CharField(choices=[('menager', 'Déchets ménagers'), ('encombrant', 'Encombrants (meubles, électros)'), ('construction', 'Gravats / Construction'), ('industriel', 'Déchets industriels'), ('liquide', 'Déchets liquides / chimiques'), ('autre', 'Autre')], default='menager', max_length=20)),
                ('niveau_urgence', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('urgent', 'Urgent'), ('critique', 'Critique (danger sanitaire)')], default='moyen', max_length=10)),
                ('description', models.TextField(help_text='Description détaillée du dépôt')),
                ('photo', models.ImageField(blank=True, help_text='Photo du dépôt sauvage', null=True, upload_to='signalements/%Y/%m/')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu'), ('rejete', 'Rejeté (faux signalement)')], default='nouveau', max_length=20)),
                ('commentaire_traitement', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolu_at', models.DateTimeField(blank=True, null=True)),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signalements', to='zones.quartier')),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='signalements/supp/%Y/%m/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_supp', to='signalements.signalement')),
            ],
        ),
    ]
