# Generated by Django 4.2.18 on 2026-06-23 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signalements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(choices=[('camion', 'Camion benne'), ('tracteur', 'Tracteur-remorque'), ('moto', 'Moto-tricycle (petites rues)')], max_length=20)),
                ('capacite_tonnes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourneeCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminee_at', models.DateTimeField(blank=True, null=True)),
                ('agent_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees_responsable', to=settings.AUTH_USER_MODEL)),
                ('signalements', models.ManyToManyField(blank=True, related_name='tournees', to='signalements.signalement')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournees', to='collectes.vehicule')),
            ],
            options={
                'ordering': ['date_prevue'],
            },
        ),
    ]
